#!/bin/bash

# Pre commit hook that prevents FORBIDDEN code from being commited.
# Add unwanted code to the FORBIDDEN array as necessary

FORBIDDEN=TODO
if grep --color=auto -n -E -- "${FORBIDDEN}" $(git ls-tree -r HEAD --name-only)
then echo "Found TODOs"; exit 1; else exit 0; fi
