#!/usr/bin/env node

const fs = require('fs');
const util = require('util');
const exec = util.promisify(require('child_process').exec);

const { argv } = process;

const data = fs.readFileSync(argv[2], { encoding: 'utf8', flag: 'r' });

async function replaceStatus() {
  const { stdout } = await exec('git status');
  const li = stdout
    .split('\n')
    .filter((e) => !e.startsWith('  (use '))
    .map((e) => `# ${e}`)
    .slice(0, -2);

  li.push('# ----------------------------------------------------------');

  console.log(data + '\n' + li.join('\n'));
}

replaceStatus();
