#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

echo "$COMMIT_MSG_FILE"
echo "$COMMIT_SOURCE"
echo "$SHA1"

if [ -z "$COMMIT_SOURCE" ]; then
    if [ -r .githooks/.badcommit ]; then
        cat .githooks/.badcommit > "$COMMIT_MSG_FILE"
        rm -f .githooks/.badcommit
        .githooks/formatMessage .githooks/.gitmessage >> "$COMMIT_MSG_FILE"
    else
        .githooks/formatMessage .githooks/.gitmessage > "$COMMIT_MSG_FILE"
    fi
fi

