import { DBLecture } from '../../src/lib/types';
import categories from './categories';
import events from './events';
import locations from './locations';
import users from './users';

const date = new Date();

const lectures: DBLecture[] = [
  {
    id: '75442486-0878-440c-9db1-a7006c25a39f',
    title: 'Nya funktioner i Azure 2021 Workshop Pecha Kucha',
    description: 'Vi tänker gå igenom lite grejer runt azure med en pecha kucha kanske.',
    lecturer: null,
    lecturerID: null,
    locationID: locations[0].id,
    eventID: null,
    duration: null,
    categoryID: categories[0].id,
    maxParticipants: null,
    requirements: 'Det är bra om man kan moln eller nåt',
    preparations: 'Ha med dig en dator typ.',
    message: null,
    tags: ['cloud', 'azure'],
    createdAt: date,
    createdBy: users[0].id,
    updatedAt: date,
    updatedBy: users[0].id,
    idea: true,
    approved: false,
    published: false,
  },
  {
    id: 'eb976a0f-146d-497d-bf4d-237a7ea79ce6',
    title: 'Är Elixir världens bästa programspråk?',
    description: 'Vi löser den stora frågan, är elixir världens bästa programspråk?',
    lecturer: 'Jonas Sjödin',
    lecturerID: users[0].id,
    locationID: locations[0].id,
    eventID: events[1].id,
    duration: 3600,
    categoryID: categories[0].id,
    maxParticipants: 100,
    requirements: 'Det är bra om man kan programmera',
    preparations: 'Ha med dig en dator typ.',
    message: null,
    tags: ['cloud'],
    idea: true,
    createdAt: date,
    createdBy: users[0].id,
    updatedAt: date,
    updatedBy: users[0].id,
    approved: false,
    published: false,
  },
  {
    id: 'eb976a0f-146d-497d-bf4d-237a7ea79ce5',
    title: 'Är Kotlin världens bästa programspråk?',
    description: 'Vi löser den stora frågan, är kotlin världens bästa programspråk?',
    lecturer: 'Mirjam Borén',
    lecturerID: users[1].id,
    locationID: locations[0].id,
    eventID: events[1].id,
    duration: 3600,
    categoryID: categories[0].id,
    maxParticipants: 100,
    requirements: 'Det är bra om man kan programmera',
    preparations: 'Ha med dig en dator typ eller nåt.',
    message: null,
    tags: ['cloud'],
    idea: true,
    createdAt: date,
    createdBy: users[1].id,
    updatedAt: date,
    updatedBy: users[1].id,
    approved: false,
    published: true,
  },
];

export default lectures;
