version: '3.7'
services:
  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kompassen2
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./postgres:/docker-entrypoint-initdb.d
volumes:
  pgdata:
    external: false
