name: Deploy

on:
  push:
    branches:
      - setting-up-cicd

jobs:
  build_and_deploy_web_app:
    runs-on: ubuntu-latest
    name: Build and deploy web app
    steps:
      - uses: actions/checkout@v2

      - name: Use caching
        uses: actions/cache@v2
        with:
          path: webapp/node_modules
          key: webapp-${{ hashFiles('webapp/package-lock.json') }}

      - name: Build and Deploy Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: /web

  build_and_deploy_server:
    runs-on: ubuntu-latest
    name: Build and deploy server
    steps:
      - uses: actions/checkout@v2

      - name: Use caching
        uses: actions/cache@v2
        with:
          path: server/node_modules
          key: server-${{ hashFiles('server/package-lock.json') }}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies and build code
        run: |
          npm install
          npm run build
          cp -r node_modules build/node_modules
          (cd build && npm prune --production)
        working-directory: server

      - name: Deploy to Azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: kompassen2
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: server/build
